### ISSUE TITLE
How to @formatjs/cli is supposed to be used?

### ISSUE THREAD

**Issue by cloud-walker** [formatjs/formatjs#1554]
Hi, I'm maintaining a 4 years old React project that uses `react-intl` and `react-intl-translations-manager` to extract messages to be used on the IntlProvider.

The problem is that `react-intl-translations-manager` is pretty unmantained, and I'm searching for a better solution.

I then found the new `@formatjs/cli`, tried it and it seems pretty fast to be honest..

But I don't know the common workflow of that (maybe an official example could help?), the cli is lacking of the following features (that translations-manager has):

- output the translations on multiple files (one per locale)
- the output is not really ready to be consumed by the IntlProvider (that needs a `Record<string, string>` to work)
- there is no diffing mechanism in order to avoid accidental overwriting of the already filled translations messages

Can someone explain me how should I structure the messages extraction mechanism? Thanks in advance!

**Comment by longlho** [comment]
Thanks a lot for the suggestions. `@formatjs/cli` is pretty barebone right now and does specifically string aggregation + ID generation. The reason we haven't invested in further downstream flow is because companies have separate pipelines to handle those things, to your point:
- `output the translations on multiple files (one per locale)`: The aggregation is typically in 1 language (`en`) so it's the matter of copying and diffing.
- `the output is not really ready to be consumed by the IntlProvider`: Yup the output is intended to be more raw & verbose to handle scenarios like duplicate messages with descriptions, or for TMS (Translation Mgmt System) to have raw info on where the string is located for debugging purposes.
- `there is no diffing mechanism in order to avoid accidental overwriting of the already filled translations messages`: Similar to idea #1, translation management is not within scope right now.

With that said, I'm not opposed to those idea. I just don't have time to tackle them all right now.

**Comment by ghostd** [comment]
Hi,

I just discovered [this project](https://github.com/akameco/extract-react-intl-messages), maybe there is something to borrow, merge (or collaborate with).

**Comment by arvinsim** [comment]
Has the diffing mechanism been implemented for `formatjs extract`?

**Comment by longlho** [comment]
@arvinsim can you create a new GH issue with some details on what you're looking for & workflow/use case?

**Comment by jjleng** [comment]
Diffing is really important for developers to iterate fast and do less chores manually. I ended up running a command like below to merge the extractions. You might need to tweak the `jq` command for your needs.

`npm run extract -- 'src/**/*.js*' --out-file /tmp/en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]' && jq -s '.[0] * .[1]' lang/en.json /tmp/en.json > /tmp/merged.json && cp /tmp/meged.json lang/en.json`

**Comment by Nosferatu31** [comment]
I have the same problem as the OP. As of now, could you tell me if this issue was handled? Is it straightforward to replace `react-intl-translations-manager` with `@formatjs/cli`? Or are there any caveats to consider?
