### ISSUE TITLE
@formatjs/cli extract intl.formatMessage not work~

### ISSUE THREAD

**Issue by shengbeiniao** [formatjs/formatjs#1679]
**Which package?**
@formatjs/cli 

**Describe the bug**
```
// test.js
export default function Comp(props) {
  const {intl} = props;
  return intl.formatMessage({
    // The whole `intl.formatMessage` is required so we can extract
    id: 'foo',
    defaultMessage: 'foo',
    description: 'bar',
  });
}

// try
$ formatjs extract test.js

// ouput
[]
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

- OS: [e.g. iOS8.1]  Mac

**Additional context**

**Comment by shengbeiniao** [comment]
```
formatjs extract --extract-from-format-message-call true test.js
```

**Comment by Haraldson** [comment]
I’m not able to extract the `formatMessage` messages either,  but as the issue text here hints at, it might be because I always destructure it from the React hook, `const { formatMessage } = useIntl()`, and thus it’s never accessed with dot notation on an object `intl`?

**Comment by longlho** [comment]
The destructuring only works in the babel plugin. Our CLI uses TypeScript transformer thus not supporting it. You'd need to call w/ `intl.formatMessage`

**Comment by Haraldson** [comment]
Just tried replacing all `useIntl` and `injectIntl` destructuring in my project and re-running `formatjs extract`. Same result, none of the `formatMessage` translations are picked up, even when they’re invoked as a property of `intl`, `intl.formatMessage({ ... })`.

My understanding is that the CLI uses TypeScript, and doesn’t require the project itself to use it (which mine doesn’t)?

**Comment by longlho** [comment]
u don't need TS, have u tried `--extract-from-format-message-call` flag?

**Comment by Haraldson** [comment]
Yes, my script includes that flag.

```zsh
formatjs extract 'src/**/*.js' --out-file .translations.json --format scripts/formatjs-translations.js --extract-from-format-message-call true
```

However, upon looking closer at the results, the extract script ‘succeeds’ with 489 translations regardless of whether the flag is there or not. It might be that it works correctly, but I expected to see different results with and without the flag.

**Comment by longlho** [comment]
Ok im confused so what is your issue? The flag might be on by default

**Comment by Haraldson** [comment]
I guess I’m confused because

1. I use more than 489 translation keys in my project. Some of them are pieced together using one or more variables, and I kind of expected this script to report the result of these expressions, instead it seems to ignore them altogether
1. I see all these reminders to ‘remember to add the `--extract-from-format-message-call` flag’ everywhere, while it is in fact enabled by default
1. I get the same result even when rolling back my changes and destructuring like before, even though I’m told that won’t work

Keep in mind, my need is probably not what `extract` is meant for; I want to make a report of all the keys used in my project so that I can delete unused ones from the translation tool and save money on having translators translate more than they have to for instance.

**Comment by longlho** [comment]
Thanks for clarifying.

1. We're not reporting those today bc of historic reasons but please create a new GH issue so we can keep track of this.
2. Yes the behavior was switch to on by default recently, we'll probably just remove this flag. Can u make a GH issue for this as well?
3. Can u create a separate GH issue with repro steps?

This GH issue is closed basically so continuing discussion here is not ideal.
