### ISSUE TITLE
Formatting Date with FormattedDate (react-intl package)

### ISSUE THREAD

**Issue by SudharakaP** [formatjs/formatjs#1712]
**Which package?**

react-intl; https://www.npmjs.com/package/react-intl

**Describe the bug**

I am trying to format the date in international format (YYYY/MM/DD) using `FormattedDate`. I could see that there's a property called, `formatMatcher` but not sure how I could use this. So I was trying to use something like, 

`<FormattedDate value={new Date()} day="2-digit" month="2-digit" year="numeric" formatMather="YYYY/MM/DD"/>`

But that doesn't seem to work. I get the error; 

```
descriptor: RangeError: Value YYYY/MM/DD out of range for Intl.DateTimeFormat options property formatMatcher
```
Could someone please let me know where I could find an example of formatting the date?

Thanks much. :smile: 

Related: https://github.com/opencollective/opencollective/issues/3096 and https://github.com/opencollective/opencollective-pdf/pull/356

**Comment by longlho** [comment]
I think you're looking for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat
It only takes in either `basic` or `best fit`

**Comment by SudharakaP** [comment]
@longlho : Thanks much for the reply. Then I seem to be looking at the wrong place. Do you by any chance know of a configuration we could use to get date in the international format (YYYY/MM/DD)?

**Comment by longlho** [comment]
The locale dictates that format (e.g some locale uses `YYYY/MM/DD` or `DD/MM/YYYY`)

**Comment by SudharakaP** [comment]
@longlho : Ah, I understand. Thanks a lot for the clarification. :+1:

**Comment by souljuse** [comment]
What if I want to force formatting, without changing localization settings? For example, I want the English months naming, but the international date format?

**Comment by longlho** [comment]
Can you provide an example?

**Comment by mgol** [comment]
@longlho An example would be using `en-US` but having date formatting specified as `dd.mm.yyyy` or `yyyy-mm-dd`. It's actually exactly what I'm doing on macOS: I'm a Polish native but I often set the locale to `en-US` so that error messages in various apps are easier to google. That said, the US date format is really confusing to me and just flipping `dd` with `mm` doesn't help as just by seeing the `/` delimiters causes me to think which format is used at the moment.

I think this is a pretty common issue. That's also why at work our app lets the user choose the preferred date format; the one matching user locale is the default but there are overrides available.
