### ISSUE TITLE
Polyfill `toLocaleDateString`

### ISSUE THREAD

**Issue by longlho** [formatjs/formatjs#1756]
**Which package?**
@formatjs/intl-datetimeformat

**Is your feature request related to a problem? Please describe.**
We should polyfill `Date.prototype.toLocaleDateString`. Right now there seems to be a pattern mismatch probably due to our best fit pattern matching.

**Comment by ertrzyiks** [comment]
There is some part of code that seems to be related, but it's commented out
https://github.com/formatjs/formatjs/blob/1ac0ad4eaf53619090be62b6dd17ac0964a2dabe/packages/intl-datetimeformat/polyfill.ts#L43-L50

Is there anything wrong with it?

**Comment by longlho** [comment]
There’s a bug in our best fit pattern selection which is why it’s commented
out

**Comment by ertrzyiks** [comment]
@longlho gotcha, now I see you created this issue as a follow-up for pushing this commented code. 

I'm new to the library so I just grepped for the best fit

https://formatjs.io/docs/polyfills/intl-numberformat/#compound-units
> The library will choose the best-fit localized pattern

and also found this option
https://github.com/formatjs/formatjs/blob/1ac0ad4eaf53619090be62b6dd17ac0964a2dabe/packages/intl-datetimeformat/src/core.ts#L260

Even if we include the commented out code fixing the simple mistakes it has, `_toLocaleDateString` function still crashes or returns wrong values. Am I right?

Anyway, can I help to fix it?

**Comment by longlho** [comment]
Definitely PR is always welcome! Thanks!

**Comment by ertrzyiks** [comment]
I unskipped the failing tests and this is what best fit pattern looks like for `en` locale.
```
pattern: '{month}/{day}/{year}, {hour}',
pattern12: '{month}/{day}/{year}, {hour} {ampm}',
```

that's why it fails with 
```
Expected: "6/16/2020"
Received: "6/16/2020, 4 AM"
```

4 AM should not be there

Need to dig deeper

**Comment by ertrzyiks** [comment]
Specs for toLocaleDateString are green if we remove that assignment `opt.hour12 = ...`, 
https://github.com/formatjs/formatjs/blob/e3c329e755aa615a9de542778626d0350487c253/packages/intl-datetimeformat/src/core.ts#L416-L419

```
  toLocaleDateString
    ✓ ko (321 ms)
    ✓ en (209 ms)
```

This assignment is not in the spec, but without it many other tests fail.
![Screenshot 2020-07-28 at 16 03 02](https://user-images.githubusercontent.com/2437969/88676006-de148480-d0eb-11ea-836c-f8bd1f614598.png)

**Comment by longlho** [comment]
That's an implementation detail for `bestFit` which is not in the spec. The bug is def in the best fit we just need to figure out how to adjust it (or reverse engineer `icu4j`/`icu4c`)

**Comment by ertrzyiks** [comment]
The low score of the appropriate pattern comes from this condition
```
if (options.hour12 && !format.hour12) {
    score -= removalPenalty;
```

as `options.hour12` is true and `format.hour12` is undefined. The simplest solution would be to wrap the `hour12` assignment in some condition and keep it undefined if we do not ask for time. I will check icu4j for ideas, thanks for the hint.

**Comment by longlho** [comment]
for the `toLocaleDateString`, `hour12` should be `false` no?

**Comment by ertrzyiks** [comment]
I added debug here:
```ts
console.log({opt, internalSlots});
opt.hour12 =
        internalSlots.hourCycle === 'h11' || internalSlots.hourCycle === 'h12';
bestFormat = bestFitFormatMatcher(opt, formats);
```

and what I got for `expect(toLocaleDateString(new Date(TS), 'en')).toBe('6/16/2020');` is:
```ts
 {
      opt: [Object: null prototype] {
        weekday: undefined,
        era: undefined,
        year: 'numeric',
        month: 'numeric',
        day: 'numeric',
        hour: undefined,
        minute: undefined,
        second: undefined,
        timeZoneName: undefined
      },
      internalSlots: [Object: null prototype] {
        locale: 'en',
        calendar: 'gregory',
        hourCycle: 'h12',
        numberingSystem: 'latn',
        dataLocale: 'en',
        timeZone: 'en',
        dateStyle: undefined,
        timeStyle: undefined
      }
    }
```
and `hourCycle: 'h12'` sets `opt.hour12` to true.

The `hour12` property of the format we need to use in that case is `undefined` though and it sounds reasonable to me as we do not talk about time at all. Even if we somehow make it false, the desired format will still have a lower score due to mismatch with the opt value.

**Comment by ertrzyiks** [comment]
It may work if we set the option `hour12` to `false` in `toLocaleDateString` and respect it in the override 👍 let me try

**Comment by longlho** [comment]
hmm I think u need to figure out why `internalSlots` has `hourCycle` set to `h11 || h12` in the `toLocaleDateString` case

**Comment by ertrzyiks** [comment]
After that hour12=false trick all the tests pass locally in #1889 

It does not fix this case though as the fix is applied locally to `toLocaleDateString`
https://github.com/formatjs/formatjs/blob/682c1c2a11d373dbd2ef39bd9f629211417f131d/packages/intl-datetimeformat/tests/index.test.ts#L27-L33

I checked icu repo and found [this place](https://github.com/unicode-org/icu/blob/dd50e38f459d84e9bf1b0c618be8483d318458ad/icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java#L642) which apparently checks date and time separately and for the date check it [ignores am/pm setting](https://github.com/unicode-org/icu/blob/dd50e38f459d84e9bf1b0c618be8483d318458ad/icu4j/main/classes/core/src/com/ibm/icu/text/DateTimePatternGenerator.java#L2318).

I will check out the status of `internalSlots` tomorrow with a fresh mind. Thanks for the help @longlho !

**Comment by ertrzyiks** [comment]
`hourCycle` gets value from the locale as per [spec](https://tc39.es/ecma402/#sec-initializedatetimeformat):

> 21. Set dateTimeFormat.[[HourCycle]] to r.[[hc]].

```
internalSlots.hourCycle = r.hc;
```

so hourCycle is correctly set to 'h12' for `en` locale.

**Comment by ertrzyiks** [comment]
Based on that research I came up with the current shape of #1889 which applies the override of `opt.hour12` conditionally.
