### ISSUE TITLE
single less than signs must be escaped

### ISSUE THREAD

**Issue by plumdumpling** [formatjs/formatjs#1845]
**Which package?**
react-intl >= v4.0.0

**Describe the bug**
The breaking change in version 4.0.0 broke translations containing a single less than sign.  

**To Reproduce**

1. Use the following translation:
```
{
  "myTranslationKey": "< {level, select, A {1} 4 {2} 3 {3} 2{6} 1{12}} hours"
}
```
2. Format the message with `intl.formatMessage({id: "myTranslationKey"})`
3. See error
```
Error: [React Intl Error FORMAT_ERROR] Error formatting message: "myTranslationKey", using id as fallback. 
Locale: en-US
MessageID: myTranslationKey
Default Message: undefined
Description: undefined

SyntaxError: Expected "#", "'", "\n", "{", argumentElement, double apostrophes, end of input, or tagElement but "<" found.
```

**Expected behavior**
It shouldn't be necessary to escape single `<` signs.

**Desktop (please complete the following information):**

- OS: macOS 10.15.4
- Browser: Google Chrome
- Version: 83.0.4103.116

**Comment by longlho** [comment]
Thanks for reporting! We'll take a look asap.

**Comment by ilovepumpkin** [comment]
Hello, I hit this issue recently as well. May I know which release contains this fix? I have tried to install react-intl@5.4.6, but it seems that this issue is still there.

**Comment by longlho** [comment]
Can u provide more details?

**Comment by ilovepumpkin** [comment]
I installed react-intl@5.4.6 and I am sure that my bundle is built with it. 

Here is my translation:
`'The prior probability of the [<span class="help-string-em" title="{cause}">{causeInShort}</span>] cause, which means the probability that the [<span class="help-string-em" title="{cause}">{causeInShort}</span>] cause will occur when there is an issue, but no information about the symptoms is available.',`

And here the error I got:
![image](https://user-images.githubusercontent.com/11310645/89755856-6c88fd00-db13-11ea-9b7f-1804e6122115.png)

So I doubt the fix is not in 5.4.6

**Comment by longlho** [comment]
We don't allow embedding HTML in messages so you have to convert your usage to rich text formatting. This issue is about escaping < & >.

**Comment by ilovepumpkin** [comment]
@longlho Before react-intl version 4, HTML tags is supported in messages because our code worked well at that time. Later I upgraded react-intl to version 4, but I am not sure this is broken since when. I didn't realize that HTML tags are not supported anymore.  Could you please provide more details about "convert your usage to rich text formatting" ? What am I supposed do to support HTML tags?

**Comment by longlho** [comment]
You can find the doc here: https://formatjs.io/docs/react-intl/components/#rich-text-formatting

It's included in v3 -> v4 Upgrade Guide: https://formatjs.io/docs/react-intl/upgrade-guide-4x#breaking-api-changes

**Comment by ilovepumpkin** [comment]
@longlho sorry that I overlooked your upgrade doc. thanks a lot for your help!

**Comment by ellie-keen** [comment]
Hi there. Was there a fix for this original issue?
I'm having the same issue where I simply want to include the less than sign as part of my translation string.
`'Input the first 16 characters (including ’<’) from the second line at the bottom'` and am getting the same errors as mentioned above.

Cheers

**Comment by longlho** [comment]
Have you tried latest version?

**Comment by ellie-keen** [comment]
Hi @longlho - yes I have this version in the package.json `^5.20.1`

**Comment by longlho** [comment]
So couple of options: you can escape it with apostrophe, encode it or set ignoreTag=true
