### ISSUE TITLE
Requiring defaultMessage on FormattedMessage forces devs to maintain source language

### ISSUE THREAD

**Issue by Floriferous** [formatjs/formatjs#1908]
This is more of a discussion, related partly to #1907 as it deals with translation management systems.

The recommended way to use `FormattedMessage` from the docs is to only set the `defaultMessage`, and optionally a `description`. The problem with that flow, is that if you want to change the default language, you have to ask a developer to change the react component, as that is the source of truth for your source-language.

When you start to translate your strings, and you have a team dedicated to copywriting and marketing, they often times not only translate strings, but also want to improve the source-language. Many tools support modifying the source language, though `react-intl` will not use those new strings, since the `defaultMessage` is hard-coded in the component (or maybe it is? But then you have duplicate strings?).

Is this process intended? Or is there something I'm missing here? 

It seems to me like the only properly decoupled translation/copywriting process is to have explicit ids everywhere, without `defaultMessage`s (though `description` could be used, but not every TMS supports them easily), and let your TMS manage all of the strings, both source-language and destination-language(s), through your marketing/product/translation teams.

Do other people want to share their workflows?

**Comment by longlho** [comment]
We encourage strings to colocate with code because that's where they'll get rendered. A string is contextual and dependent on its usage, which includes distinguishing between label vs button vs header, along with string manipulation like locale-aware truncation & sorting. This is not the source of truth though. That's whatever marketing decides.

The process of augmenting source language is out of our scope. String extraction gives you location of that string you can build tooling around that.

This is the workflow that Yahoo & Dropbox use. I'm not saying it's the best, but it's worked very well for large engineering orgs.

**Comment by longlho** [comment]
Another piece of context is that Dropbox used to have a versioning system for strings but that was gutted out because the complexity isn't worth it, and it introduced confusion more than anything due to cache propagation issues.

**Comment by jensbodal** [comment]
> The process of augmenting source language is out of our scope. String extraction gives you location of that string you can build tooling around that.

Are there any examples of this? 

Let’s say our default language is english, we have a bunch of `messages` files that live next to the components they are related to.  We generate the `en-US.json` files with the sole purpose of sending them to a native english speaker to review the grammar and wording. They make changes to the `en-US.json` file and send them back to us.

The expectation here is that we then need to write custom tooling to re-ingest their strings into our messages which declared the default strings?

**Comment by longlho** [comment]
No you should serve your curated messages just like any other language. We don't assume `defaultMessage` to be English. The locale of `defaultMessage` is specified in `defaultLocale`

**Comment by jensbodal** [comment]
Sorry I wasn’t saying you assume any default language or locale.

I’m saying that we want the language and locale that we use for our default messages to be curated.  Text can change over time and it would seem unnecessary to require a developers time to update a default message JavaScript/typescript file to then update the default language/locale file.  We’d like them to remain in sync, with the source of truth coming from the eventual existence of the JSON messages file.

if this doesn’t make sense I’m having a really hard time understanding why.

**Comment by longlho** [comment]
Hmm I'm not sure I fully understand the workflow. How do you verify the curated messages look & fit correctly? Wouldn't that also require dev time?

For your use case you can still declare IDs only without `defaultMessage`. We still fully support it, just not recommending it.

**Comment by jensbodal** [comment]
The dev time for the initial curated message, sure.  But let's say we have some strings where the wording changes ever so slightly, .e.g. punctuation, capitalization, or rewording in similar number of words, but the original work was "correct" as far as the initial ask goes.

```
Astronauts going to space. => Astronauts going to space
Managing Your Risk => Managing your risk
etc.
```

When this goes to stakeholder review, and some of these strings are decided to need updating, it would seem to make sense to manage these from a product/UX standpoint rather than a developer standpoint.  

If we need to completely rework how the text is displayed, add/remove parameters, etc., then it would make sense for it to go back to a developer.

Additionally, translating these messages in general would have the same issue of whether or not they look and fit correctly.  So regardless of best effort for responsive design, you'll always need to review how the app looks and feels within each translation.

---

> For your use case you can still declare IDs only without defaultMessage. We still fully support it, just not recommending it.

This was the path I think I am headed down.  But it still feels like the consensus is that this is the "wrong way" to do it, but given the original ask of a TMS managing all the strings post-development, I'm not sure how else this could be accomplished. 

The idea I had was

1. Developer's write original content using `messages` files using an `id` and `defaultMessage`
2. Post-commit or some other hook runs the extract messages script, this script will:
    - Pull default messages into a chose default language and locale (as seems to be the normal process)
    - After pulling messages, delete the `defaultMessage` from the relevant `messages` file
3. During development the app will read from the default message in messages file if present, otherwise will read from default language and locale
4. Any future additions to the `messages` file (new IDs, removal of IDs) would appropriately add/remove related messages from JSON files 
5. Adding a new defaultMessage to an existing message ID would either throw an error or possibly start the process for re-translating a string

This is a rough idea of how I think it could work, with the most difficult part I'd imagine being the removal of the defaultMessage from the relevant messages file.
