### ISSUE TITLE
CLI extraction ignores template strings

### ISSUE THREAD

**Issue by lucasff** [formatjs/formatjs#2028]
In `@formatjs/cli`, when using the extraction command, all usages of `defineMessages` or `FormattedMessage` that contain a string using Node template strings are ignored.

```
key: {
  id: 'niceKeyName',
  defaultMessage: `You can find your information:\n
  some gibberish here`,
},
```

output of using `formatjs compile`

```
key: {}
```

If any error, at least I'd expect a valid object like:

```
key: {
  string: ''
}
```

using the Transifex format in this case

**Comment by longlho** [comment]
Yes it's only extracting from string literal. Template literals have a lot of footguns that we haven't supported it, especially with unintentional whitespaces due to auto indentation at newline. Also newline characters and sentence breaking are i18n-sensitive. I generally recommend using string literal with full sentences.

**Comment by lucasff** [comment]
Can @formatjs do some sort of in-memory usage of babel to parse the strings from the babel-parsed output?

**Comment by longlho** [comment]
Oh it's doable we just actively choose not support it based on our experience with large codebases and how engineers assume the way template literals work.

**Comment by longlho** [comment]
With that said I'll keep the issue open and if it's popular we'll reconsider

**Comment by cafca** [comment]
My usecase involves managing translations of articles that are composed of paragraphs. I currently assign each paragraph to format.js message. Without template literals, the source files become unreadable because the long lines containing the messages cannot be broken into multiple lines. I would appreciate it a lot if format.js was able to handle template literals.

**Comment by longlho** [comment]
Ok that's fair we'll take a look.

**Comment by xsburg** [comment]
In my use case we generated IDs manually (intentionally) and used template strings to avoid repeating the namespace prefix, e.g. ``{ id: `${componentPrefix}.title` }``. `babel-plugin-react-intl` had a limited but good support for that.

I really like the idea of doing extraction with a separate CLI but the lack of old features leaves 'no upgrade' as the only choice for now.

**Comment by longlho** [comment]
What was limited support btw?

**Comment by xsburg** [comment]
@longlho, not sure what was the full scope that the plugin supported, but in my case:
- template strings in id's and defaultMessage: ``id=`${componentPrefix}.title` ``
- using variables in template string, which are defined somewhere in scope (inside the file) and initialized as _simple string literals_ (so nothing fancy like more template strings etc).
- using string concatenation in `defaultMessage`: ``defaultMessage={'foo' + 'bar'}``

These simple features, although far from comprehensive, give enough freedom so that I personally never thought about restrictions.
