### ISSUE TITLE
TypeError: ecma402_abstract_1.invariant is not a function

### ISSUE THREAD

**Issue by influento** [formatjs/formatjs#2030]
**Which package?**
react-intl@5.6.6

**Describe the bug**
Hello,
Starting from 5.6.6 we are getting error **Uncaught [TypeError: ecma402_abstract_1.invariant is not a function].** 
With later version we also started to get this error **intl_1.createIntlCache is not a function**
Both of those dependencies are relatively new and were published added 6 and 3 days ago.
https://www.npmjs.com/package/@formatjs/ecma402-abstract
https://www.npmjs.com/package/@formatjs/intl

Full call stack 

**First error**
https://pastebin.com/QM3ZhjmM

**Second error**
https://pastebin.com/StdVhuWz

Currently we are using 5.6.5 to avoid both errors.

**Comment by longlho** [comment]
This seems to be an issue in bundling. Do you have a repro?

**Comment by influento** [comment]
@longlho 
I have in our project.
https://github.com/Orckestra/orc-shared/tree/develop (make sure you are on develop branch)
for repro it's enough to just run all tests (you can use **npm run coverage** command for it)

**Comment by influento** [comment]
@longlho 
We updated develop branch to use 5.6.5 so, there won't be repro in new commits anymore. 
Do you need any extra information?

**Comment by longlho** [comment]
If I change to 5.6.6 the issue will happen?

**Comment by influento** [comment]
@longlho 
Yes this one will start to happen
Uncaught [TypeError: ecma402_abstract_1.invariant is not a function]

And for one of later versions (not sure which one exactly) this issue will start to happen
intl_1.createIntlCache is not a function

**Comment by pyrocat101** [comment]
@Crispried 

I tried checking out https://github.com/Orckestra/orc-shared/tree/c58c73ef46cd4be135855b54e165afddb8dd9e40 and ran `yarn coverage`. Because the project has no lock file I have to manually pin `react-intl` to 5.6.6.

The problem lies in that a dependency is incorrectly resolved in `@formatjs/ecma402-abstract` **by Jest**: https://unpkg.com/@formatjs/ecma402-abstract@1.2.0/index.js

If you modify this file by adding a `console.log(require.resolve('./src/utils'))` you will see that it is resolved to `orc-shared/src/utils/index.js` when you ran Jest test. But if you just use NodeJS REPL to require `@formatjs/ecma402-abstract`, it prints out the correctly resolved path. I don't know whether this is a bug in Jest or is it because of the usage of `jest.mock` in your tests.

I am closing this since there is no evidence that it is a bug in our package.
