### ISSUE TITLE
 Polyfilled and native browser Intl.NumberFormat APIs works differently

### ISSUE THREAD

**Issue by hvozdyk** [formatjs/formatjs#2157]
**Which package?**

`@formatjs/intl-numberformat`

**Describe the bug**

 Polyfilled and native browser `Intl.NumberFormat` APIs work differently under certain circumstances 

**To Reproduce**
1. Plug in `@formatjs/intl-numberformat` polyfill into the page
2. Open browser console 
3. Call `new Intl.NumberFormat('en-US', { maximumFractionDigits: 20 }).format(1.1)` (also reproduced when `maximumFractionDigits` equals 17 or 18)
4. See result: "1.1000000000000002"

**Expected behavior**

See result: "1.1" (The same which is returned by native browser `Intl.NumberFormat` API)

**Desktop:**

- macOS Catalina 10.15.6
- Safari
- 14.0 (15610.1.28.1.9, 15610)

**Additional context**

Check out example https://stackblitz.com/edit/js-upqi1h?file=index.js in browsers (e.g: Safari Vs Chrome)

**Comment by pyrocat101** [comment]
The bug comes from the implementation of [ToRawFixed][].
According to the [spec][]:

> 2. Let n be an integer for which the exact mathematical value of n ÷ 10^f – x is as close to zero as possible. If there are two such n, pick the larger n.

`f` is 20 in your case, and to compute `n`, we naively compute `Math.round(1.1 * 10 ** 20)`, which is actually quite big for a IEEE 754 double... So the resulting n loses some precision.

ICU uses BigDecimal so they do not have to worry about this... Let me think if there is a way to workaround the issue without introducing arbitrary precision values.

[ToRawFixed]: https://github.com/formatjs/formatjs/blob/6794d6314c7f9e4bc6ec7008542491c70d3706ac/packages/ecma402-abstract/src/NumberFormat/ToRawFixed.ts#L16-L18
[spec]: https://tc39.es/ecma402/#sec-torawfixed

**Comment by pyrocat101** [comment]
After tinkering around this for a while, I am not sure if there is a good solution. The fraction part of 1.1 cannot be represented accurately in IEEE 754. Using high `maximumFractionDigits` with native floating point won't work very well.

I am open to PR if anybody has good ideas :)
