### ISSUE TITLE
Missing Locale data for pt-BR (Portuguese (Brazil))

### ISSUE THREAD

**Issue by wessberg** [formatjs/formatjs#2237]
**Which package?**
`intl-datetimeformat`, `intl-displaynames`, `intl-listformat`, `intl-numberformat`, `intl-pluralrules`, `intl-relativetimeformat`

**Is your feature request related to a problem? Please describe.**
Hi there. Good work on implementing Ecma-402!

I noticed that none of your polyfills provide locale data for `pt-BR` (Portuguese (Brazil)), a language spoken by almost 200 million people.

**Describe the solution you'd like**
I think your polyfills should provide locale data for `pt-br`

**Describe alternatives you've considered**
None

**Comment by longlho** [comment]
I believe that's just pt

**Comment by wessberg** [comment]
Not quite. `pt` is Portuguese (Portugal) whereas `pt-BR` is Portuguese (Brazil)

**Comment by longlho** [comment]
I get that but from a data perspective pt is pt-BR, similarly en is en-US/en-001

**Comment by wessberg** [comment]
I'm not intimately familiar with neither variant of Portuguese, so I don't know if there are any cases in which the formatting differs. But if there are no differences, then I agree that using just `pt` should be sufficient. In that case, this issue can be closed.

**Comment by dchiba** [comment]
There is no need to add locale data for Brazilian Portuguese locale under `pt-BR` because it is available under `pt`. In Unicode CLDR, a language-only locale such as `pt` and `en` is to hold data for the locale of the language's most dominant variant or region, like `pt-BR` and `en-US`, respectively. This concept is called [Default Content Locale](http://cldr.unicode.org/translation/translation-guide-general/default-content) and the way CLDR organizes locale data follows this principle. FormatJS adopts CLDR so locale data for Brazilian Portuguese are provided under `pt`.
