### ISSUE TITLE
Console errors when using <FormatMessage/> without `id`

### ISSUE THREAD

**Issue by samajammin** [formatjs/formatjs#2589]
Hey folks - first off, thanks for building this incredible package!

## Which package?
`react-intl`

## Describe the bug

I'm using `<FormattedMessage />` with no `id`, only a `defaultMessage`, as described in the docs:
https://formatjs.io/docs/getting-started/message-declaration#using-react-api-formattedmessage

e.g.
```
<FormattedMessage defaultMessage="Checklist" />
```

### Codesandbox URL

Here's the branch of our repo:

https://github.com/ethereum/eth2.0-deposit/tree/translations

### Reproducible Steps/Repo

1. Start the app: `yarn start`
2. Go to any page in the browser (e.g. http://localhost:3000/en/)
3. The strings display as expected in the browser but yield many console errors, e.g.

```
index.js:1 Error: [@formatjs/intl Error FORMAT_ERROR] Error formatting message: "eyK2E3", using default message as fallback. 
Locale: en
MessageID: eyK2E3
Default Message: [object Object]
Description: undefined 
 

A message must be provided as a String or AST.
TypeError: A message must be provided as a String or AST.
    at new IntlMessageFormat (core.js:144)
```

## Expected behavior
Expecting no console errors. Other than that, everything works as expected!

## Screenshots

![Image 2021-02-09 at 3 48 13 PM](https://user-images.githubusercontent.com/8097623/107443758-4528e200-6aee-11eb-96d9-2d56dd6579cf.jpg)

## Desktop (please complete the following information):

- OS: macOS Catalina v10.15.7
- Browser: Brave
- Version: Version 1.19.88 Chromium: 88.0.4324.96 (Official Build) (x86_64)

## Additional context

We're running a TypeScript app using CRA w/ `rescripts` as recommended by @longlho here:
https://github.com/formatjs/formatjs/issues/1901#issuecomment-766515227

**Comment by longlho** [comment]
The root cause is that you're using the raw lang json file meant for translation vendor (crowdin) instead of simple key-value format that we expect. Therefore you'd need to `compile` using `crowdin` formatter as well. See https://formatjs.io/docs/tooling/cli#compilation for docs.

For your case, add a compile step like `formatjs compile src/intl/en.json --format crowdin --outfile compiled-lang/en.json --ast`. And then you can import `compiled-lang/en.json` and pass back to us.

See https://formatjs.io/docs/getting-started/message-distribution for a more wholistic pipeline setup as well.

Hope that helps.

**Comment by samajammin** [comment]
Awesome! Thank you @longlho for the quick support here. Your recommendation worked like a charm.

Here's our PR to fix for those who hit a similar issue: https://github.com/ethereum/eth2.0-deposit/pull/362

**Comment by TimDaub** [comment]
> formatjs compile src/intl/en.json --format crowdin --outfile compiled-lang/en.json --ast

minor error: `--out-file`
