### ISSUE TITLE
React-intl pass inputs to textComponent

### ISSUE THREAD

**Issue by alexcibotari** [formatjs/formatjs#2856]
## Which package?
React-intl

## Describe the bug
I would like to add a capability for **textComponent** to receive parent props
For example **FormattedMessage** should pass all props to the **textComponent**, otherwise it is a dummy component, and I would like to add additional features to all my localized values

## To Reproduce
Add any dummy React Component to **textComponent** configuration

## Expected behavior
I as a developer would like to receive in the **textComponent** all props in order to enchase my application with additional features base on **react-intl** features

**Comment by longlho** [comment]
`textComponent` is pretty much a legacy artifact since before render props was a thing. It's also more  for solving the React Native issue of not being able to render a component that returns a `string` (it needs `Text` element). So we won't be extending this functionality any further. Please write a wrapper component if you want to have custom attributes.
