### ISSUE TITLE
Feature request - currency format in  ECMA-376 numFmt for locale/currency

### ISSUE THREAD

**Issue by chulkilee** [formatjs/formatjs#2885]
Various doc formats (such as XLSX) support ECMA-376 numFmt. However, building right numFmt for each currency is challenging - and I couldn't find any existing resources.

As formatjs already implements currency formatting for Intl.. I'm wondering we can leverage this!

Related

- https://github.com/SheetJS/ssf
- https://github.com/exceljs/exceljs
- https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/0e59abdb-7f4e-48fc-9b89-67832fa11789

**Comment by longlho** [comment]
what specifically are you looking for? Not all number formats from CLDR can be translated to ECMA-376 (e.g `# ?/?`). Are you looking for a function that takes ECMA-402 `NumberFormatOptions` and turn it into `ECMA-376` number format for currency?

**Comment by chulkilee** [comment]
For the mvp it would be nice to have a function to return the default currency format for (currency, locale)... or just (currency)? I'm not sure there is a spec for currency format without locale.

For example, when I select a currency format in such softwares I see the default option for the given currency is provided. Not sure they use different format per locale though.

**Comment by longlho** [comment]
So there are a fixed number of built-in `numFmt`s per ECMA-376 Part 1 Section 18.8.30

> When values not present in the lists below are used, the behavior is implementation-defined.
Ids not specified in the listing, such as 5, 6, 7, and 8, shall follow the number format specified by the formatCode
attribute.

| ID | formatCode |
|--|--|
|0| General
|1| 0
|2| 0.00
|3| #,##0
|4| #,##0.00
|9| 0%
|10|0.00%
|11| 0.00E+00
|12| # ?/?
|13| # ??/??
|14| mm-dd-yy
|15| d-mmm-yy
|16| d-mmm
|17| mmm-yy
|18| h:mm AM/PM
|19| h:mm:ss AM/PM
|20| h:mm
|21| h:mm:ss
|22| m/d/yy h:mm
|37| #,##0 ;(#,##0)
|38| #,##0 ;\[Red](#,##0)
|39| #,##0.00;(#,##0.00)
|40| #,##0.00;\[Red](#,##0.00)
|45| mm:ss
|46| [h]:mm:ss
|47| mmss.0
|48| ##0.0E+0
|49| @

Out of those formats, in ECMA-402:
- 37, 38, 39, 40 are `accounting` `currencySign`
- 1, 2, 3, 4 are `decimal` `style`
- 9, 10 are `percent` `style`
- 11, 48 are `scientific` `notation`

For your use cases looks like you need `currency` style but do you need `accounting` sign? (basically instead of `-$500` it'd be `($500)`)

**Comment by chulkilee** [comment]
My cases is to display currency values so just `currency` style.  Is ECMA-376 powerful enough to represent Intl currency format? If not, probably I need to just use simplest format but with different currency signs.

**Comment by longlho** [comment]
ECMA-376 defers things like grouping/negative symbol (`,`, `.` or `-`) to each locale so it's fairly vague. Ok supporting just currency shouldn't be hard so I'll take a look.

**Comment by longlho** [comment]
I just released `@formatjs/ecma376` so give it a try. Sorry for the lack of doc but it's pretty simple rn. The tests should provide some example usages: https://github.com/formatjs/formatjs/blob/main/packages/ecma376/tests/index.test.ts
