### ISSUE TITLE
Format date placeholder

### ISSUE THREAD

**Issue by mancristiana** [formatjs/formatjs#2922]
This is a feature request for formatting a date placeholder depending on the locale. The use case is for a date input with a placeholder representing the expected format. For example, `dd/mm/yy` or `mm/dd/yy`.

Currently, [formatDate](https://formatjs.io/docs/intl#formatdate) accepts a value that can be parsed as a date and returns the formatted date according to the selected locale.

So it would be useful to have some utility or option to get the corresponding date placeholder representing the expected date format for the selected locale.

**Comment by longlho** [comment]
So that's really not i18n-safe since you're effectively forcing the format to be of a specific locale, which might or might not be correct. Therefore we don't have any plan to support that right now.

At the Unicode level there's a concept of [skeleton](https://www.unicode.org/reports/tr35/tr35-44/tr35-dates.html#Date_Field_Symbol_Table) that looks like `yMd` and for `en-US` it's `M/d/y` and `en-GB` it's `d/M/y`.
