### ISSUE TITLE
formatjs not compatible with ES Modules

### ISSUE THREAD

**Issue by denisaStefan** [formatjs/formatjs#2961]
I tried to integrate the formatjs library in my project, but I ran into problems because of the following:
The script that uses the library is loaded as a module. However, this is not working with the browser throwing the following error:
 🚧 Browser logs on Chromium:
      TypeError: Failed to fetch dynamically imported module
 🚧 Browser logs on Webkit:
      TypeError: 'application/json' is not a valid JavaScript MIME type.
 🚧 Browser logs on Firefox:
      TypeError: error loading dynamically imported module

The error is caused by the line:
`digitMapping = tslib_1.__importStar(require("./digit-mapping.json"));`

Modules are expecting js files and do not consider `json` a valid JavaScript MIME type.

I believe it could be beneficial to multiple people to have the imports changed so that the library could be loaded as module.

Thanks!

**Comment by longlho** [comment]
do you have a repro repo?

**Comment by davidclark87** [comment]
I'm hitting this too, I will try to produce a minimal repro example tomorrow.

The issue is this is not a standard import - you can't import JSON (unless bundling your code with a tool like webpack):
```js
import * as digitMapping from './digit-mapping.json'
```

https://github.com/formatjs/formatjs/blob/main/packages/ecma402-abstract/NumberFormat/format_to_parts.ts#L18
