### ISSUE TITLE
Questions: Documentation / Usage Confusion

### ISSUE THREAD

**Issue by petertellgren** [formatjs/formatjs#3225]
Hello, 
We're trying our best to integrate react-intl in a very young [Vitejs](https://vitejs.dev/) project written in TS exclusively. 

We're quite confused when it comes to the best practice regarding the id attribute in both our `<FormattedMessage />` and `intl.formatMessage({` call sites.

If we try to omit the ID from these we are met with the error:
```
Uncaught Error: [@formatjs/intl] An `id` must be provided to format a message. You can either:
1. Configure your build toolchain with [babel-plugin-formatjs](https://formatjs.io/docs/tooling/babel-plugin)
or [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) OR
2. Configure your `eslint` config to include [eslint-plugin-formatjs](https://formatjs.io/docs/tooling/linter#enforce-id)
to autofix this issue
```

though helpful only the 2nd option `eslint` we get working. This will generate an id each time we save the file. having it committed to the source code. 

Forgive my ignorance but I would much prefer the `eslint` rule of `no-id` and having them generated both in development as well as in build. Which I assume is what the 1st option would allow me to do?

some additional questions: 
1. What is the recommended (if there is one) way to use `@formatjs/ts-transformer` in a vitejs (esbuild) project. 
2. in [@formatjs/ts-transformer](https://formatjs.io/docs/tooling/ts-transformer) the install instructions to install as runtime dependency where as https://formatjs.io/docs/guides/bundler-plugins#using-formatjsts-transformer installs it as a development dependency. Is this an oversight or based on use case?

**Comment by longlho** [comment]
do you have a codesandbox?

**Comment by asvny** [comment]
Since vite is esbuild focussed .. it is little annoying to include babel just for the sake of react-intl. Facing the same problem

**Comment by longlho** [comment]
esbuild doesn't have a AST transformer plugin/API so it's basically impossible. See https://github.com/evanw/esbuild/issues/111

**Comment by Sharsie** [comment]
@longlho I understand why this is not supported, but would definitely welcome a mention in the docs that esbuild is not supported to save people time on debugging or trying to find a solution, since switching to Vite makes sense for a lot of us. I would also welcome something to track (be it an issue or a documentation mention) in the future in case the circumstances change or someone comes up with a solution that could deliver the automatic message ID generation for these types of projects.
Thanks for investing your time in the issue though.

**Comment by raybrownco** [comment]
I was able to get FormatJS working in Vite via a method that I haven't seen documented anywhere. 

I'm using the [@vitejs/plugin-react](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react) plugin to enable React support in Vite, and it turns out that this plugin has [configuration options for Babel](https://github.com/vitejs/vite-plugin-react/tree/main/packages/plugin-react#babel). So, we can simply follow [the instructions for Babel](https://formatjs.io/docs/getting-started/installation#babel), but without needing to install and configure Babel:

```ts
// vite.config.ts:
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: [
          [
            'formatjs',
            {
              idInterpolationPattern: '[sha512:contenthash:base64:6]',
              ast: true,
            },
          ],
        ]
      },
    }),
  ],
})
```

It's less than ideal to require Babel config in a project that otherwise doesn't use it, but...it works!

**Comment by Amansaxena001** [comment]
Guys I need help can you please check this https://github.com/formatjs/formatjs/issues/5972? Is there no way that this babel plugin wont run if we use a wrapper component and call formatMessage inside it? as the common comp accepts text from props so the plugin could not determine how to extract?
