### ISSUE TITLE
Type safety: catching variable type mismatches at build time

### ISSUE THREAD

**Issue by OliverJAsh** [formatjs/formatjs#3346]
## Problem

We are beginning to integrate FormatJS/`react-intl` at [Unsplash](https://unsplash.com/) and one of the big challenges we are facing is the lack of type safety. For example, consider this React component:

```tsx
import * as React from "react";
import { FormattedMessage } from "react-intl";

const Test = () => (
    <FormattedMessage
        defaultMessage="{name} uploaded {gender, select, male {his} female {her} other {their}} <firstPhotoLink>first photo</firstPhotoLink> on {firstUploadDate, date, long}. In total they have {totalPhotos, plural, one {uploaded # photo} other {uploaded # photos}}."
        values={{
            name: name,
            gender: gender,
            firstPhotoLink: (xs: Array<React.ReactNode>) => (
                <a href={createPhotosPagePath(photoId)}>{xs}</a>
            ),
            firstUploadDate,
            totalPhotos,
        }}
    />
```

The `values` must match the variables defined inside the ICU Message, which can be enforced using the [`enforce-placeholders`](https://formatjs.io/docs/tooling/linter/#enforce-placeholders) ESLint rule. However, this only validates that all of the variables have been provided—it doesn't check that the type of each value provided in `values` matches the type of the variable inside the ICU Message.

For example, we could mistakingly pass an object for a variable which requires a `number`:

```tsx
const Test: React.FC = () => (
    <FormattedMessage
        defaultMessage="You have uploaded {myNumber, plural, one {# photo} other {# photos}}"
        values={{
            myNumber: {},
        }}
    />
);
```

There is no error at compile time nor runtime. The user will see the number variable rendered as `NaN`, e.g. `You have uploaded NaN photos`.

Another example: we could mistakingly pass a `number` for a variable which requires a function:

```tsx
const Test: React.FC = () => (
    <FormattedMessage
        defaultMessage="Click <myElement>here</myElement>"
        values={{
            myElement: 123,
        }}
    />
);
```

Again, there is no error at compile time. This time we do get a runtime error: `Value for "myElement" must be of type function`.

It should be possible to catch these issues at build time rather than at runtime.

## Ideas

[Lingui](https://lingui.js.org/) solves this problem by embracing JSX. Instead of writing the ICU Message as a string ourselves, we can just write normal JSX. Upon extraction this will be converted to an ICU Message string.

(This idea has been discussed before: https://github.com/formatjs/formatjs/issues/89#issuecomment-78344436.)

```tsx
import { Plural, Trans } from "@lingui/macro";
import * as React from "react";

const Test: React.FC = () => (
    <Trans>
        You have uploaded <Plural value={123} one="# photo" other="# photos" />
    </Trans>
);
```

This will extract as the following ICU Message: `You have uploaded {0, plural, one {# photo} other {# photos}}`.

We can't make the mistake of accidentally passing the wrong type like we could with FormatJS. The `Plural` component's `value` prop requires a `number`. If we try to pass something else, TypeScript will return a type error:

```tsx
const Test: React.FC = () => (
    <Trans>
        {/* TypeScript error: Type '{}' is not assignable to type 'number'. */}
        You have uploaded <Plural value={{}} one="# photo" other="# photos" />
    </Trans>
);
```

This is how the link example works in Lingui:

```tsx
const Test: React.FC = () => (
    <Trans>
        Click <a href="#test">here</a>
    </Trans>
);
```

This will extract as the following ICU Message: `Click <0>here</0>`

Again, we can't make the mistake of accidentally passing the wrong type like we could with FormatJS because we're rendering the link element inline.

[FBT](https://facebook.github.io/fbt/) seems to use a similar approach. Example: https://github.com/facebook/fbt/blob/9105216ba94092cc16af041ec3b0371d5841e7a0/demo-app/src/example/Example.react.js#L298-L320

**Comment by longlho** [comment]
This is a common drawback when 2 DSLs interact with each other. `lingui`/`fbt` approach basically uses 1 DSL to generate another DSL and our approach + [fluent](https://projectfluent.org/) + basically most other i18n implementations in other languages are to keep message format raw to the spec. I think tradeoffs have been discussed in the GH issue you posted. 

Having raw ICU message allows us to manipulate and do static analysis so messages are both translator & dev-friendly (e.g [preventing complex selectors](https://formatjs.io/docs/tooling/linter#no-complex-selectors) and such).

Raw messages are also more authoring-friendly since they aren't owned by devs most of the time, but rather copywriter/PMs that have to tweak those messages cross platform. When I had discussions internally at Dropbox people actually don't wanna take the cost of having to convert ICU -> React in source code and would much prefer copy-pasta messages from an external source.

I don't really have a good answer other than this can be caught during testing.

**Comment by OliverJAsh** [comment]
Thanks for the detailed reply!

> Having raw ICU message allows us to manipulate and do static analysis so messages are both translator & dev-friendly (e.g [preventing complex selectors](https://formatjs.io/docs/tooling/linter#no-complex-selectors) and such).

Wouldn't this still be possible with JSX? Lingui demonstrates that it's possible to use static analysis to extract ICU Message strings from JSX. If we take this one step further, I think a linter would be able to do something similar? For example, `no-complex-selectors` could convert the JSX to an ICU Message AST before it runs any logic to determine whether or not the (generated) selector is complex.

I appreciate your point about raw messages being more author friendly. Although, I think it really depends on the application and company process. At Unsplash, most of our text is heavily intertwined with DOM elements (e.g. inside or surrounding buttons), so it makes more sense to define text inside of components which will be owned by developers rather than copywriters/PMs.

Perhaps we could have the best of both, i.e. the option to define ICU Messages as strings _or_ using JSX. Where text needs to be managed externally (e.g. by copywriters) we could use ICU Message strings, and where text is heavily intertwined with application logic (e.g. inside or surrounding buttons) we could use JSX.

**Comment by longlho** [comment]
it's rather a heavy maintenance effort on myself to support that tbh, since we're effectively would be porting that convention to 4 different AST parsers (eslint, babel, tsc & swc) while we know for sure the solution stops scaling past a certain eng org size.

**Comment by longlho** [comment]
@OliverJAsh  hmm I think this might work: https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgJwM4QQUQQg9ggPGqCAD2AgDsATJKJYBASzIHMA+KAXigG9DMcAuKHQCu0AL5QAZFDQBYAFChIsRCngI4AWyS4AKoRLkqNOoyYAaFRu0HSlarQbMOUMhABuqNp0dnbR6n0AfisUdD48AHJ9TWFaKAAjaDgoABt6Ug1UoXAISLZBfWI7YwADABIuRgAzVFgECGr6IjEuSpq69S0xMXayWoQoACUIWjFSqBD1NUQtHRHaSy6bAB8rLQL17QUlaF0sAHkEgCtcGH97EydWFx4AbQBrKEZYAF0oQV9nCQUFRkzqnAAMbQACyoyQcCYEAAIqMgQwwMAcHoLsYvjcuAooDioBRGnBhKlgOCkJDoYUFGJfvJ8UDUohoNVhGQgcB6FgyFBqjhNHASRCoRBUcUAlczCwABQPCAgQSk8mw+GI5F4XQsSxgWbaQqHE5nVQQZY6dUsACUn1MzAA3DSeQg+QKyULJVx8YCiU7FYIAEQACQgqVSWG4TWQwAAcloIBIuAzaFHNDHLAB3QNArBJgCEPrEli4YYT0cEkR5WEiUDEZoU9sdCpdboJnvrFKg-sDwdD9HDiZj3HjkejeagadSGezufzhcHSZLZcilgHvZLCUQFarCiAA

granted we have to kinda port the ICU spec to it

**Comment by OliverJAsh** [comment]
I saw a similar example shared here by @gabro: https://github.com/microsoft/TypeScript/issues/32063#issuecomment-749434013.

@gabro How did this approach turn out for you? I guess we would essentially have to write an ICU Message parser using TypeScript's template literal types? Is that even possible (for the full range of syntax)?

**Comment by longlho** [comment]
Actually this is the same as enforce-placeholder at best and still won't give you parameter type

**Comment by gabro** [comment]
@OliverJAsh here's our last attempt: https://www.typescriptlang.org/play?#code/C4TwDgpgBACghgJwM4QQUQQg9ggPGqCAD2AgDsATJKJYBASzIHMA+KAXigG9DMcAuKHQCu0AL5QAZFDQBuALAAoUJFiIU8BHAC2SXEqhQAKoRLkqNOoyYAaA2q27TpStVoNmHKGQgA3VEpsnO7WzubURvYA-A4o6Hx4AEQm2sK0UABG0HBQADb0pFq5QuAQiSz2gibELhYABgAkXIwAZqhQAPpiXE2t7Zo6YmK9ZG0IUABKELRiddEOOmGuUI3No+0AkmQ+CAPaYjYjY50HR+1dc4qGhjFT6TXhK1BYwAAW7T1rx11DZ+NTcFyd2As3s1ygMU0GkQOj0AKB02ANgWTgAPlAtjs9hUruCoIIoRA9nDEcjiVB0ZjUNiwfjYkSYbpcMCyYzqOiabiCWyFIolCpoEYsAB5DIAK1wMCWFhCzCC3CgAG0ANZQRiwAC6gllTCgYl5SgAxlgyPcyF4uPZEgAZLBMRgAOgA7hBcsbtBAALLTJBwJhlQSJAASrtyWG4LXoyGAADkdBAJFxcnBaHGPQcoC63VgPQBCRJ2RQSFNQY2m4AG5SlKAAQS8hOJuGDofDXEj0bTCczrvdEHzLF5AHpB4YAHpRfnVgBC9fUDMcembuTDEajqfjieT6-TyKzvf7Q5HUHHk9UAGFZ8h57Cm0Z3hGsFgJMaKNBGHFSBQ1dRGMbMBBDWAB1uAQCBtDgRhrBrYBSG0MBgCQZEwFyYQimRdgAEZuDgGCwPgiQXnecYuBw2D4KQIY8ggFogPKQ8xwnKtVAAMUvaEFybX8cFAwDgK4UDwMg5hoLIhCkJQtCOCwkjcLgkFnjeD5SLwhDKNyajaIHJRhwY09oAAcTY68mWSe820fZ8sFfNVTVQT9vxsv8eKAkCwIgsgoNk8jxNQwF0Ok5S5IIxTiMC8i1I0viwywXIxDo7SjxPJjoCDIzG1M6AwAYQ03yQQQuCy+gcuRMhhG0LIEGRfh+ENVDQLIQ0QEHNAAFUJjirTFB049GKUV9DWTUCoBaYQGuAegTWGnBwOAb0kF9f1cAAaWlahlQgEAsBaEpIC2wgyBYAAKex1pAQQlsLQwwDZKoRXFSU50bAU9vIRUlo1FgcQASm1KxmErFpppwuaFogQ6bTtR09xzL0fT9MpkR4dttwgQNAawRI9S+3lAYQGaQfh8HbXtMhnR7GGCf9AsFWR2N4zRx9qa3OmPUDDJEExsRsaAA

It covers a bunch of common cases, but I don't think it's spans the full range of the ICU syntax.

We never ended up using in production due to https://github.com/microsoft/TypeScript/issues/32063 and the lack of will/time to work around it.
