### ISSUE TITLE
@formatjs/cli extract using custom format is throwing error

### ISSUE THREAD

**Issue by marwen-cherif** [formatjs/formatjs#3645]
## Which package?
@formatjs/cli

## Describe the bug

Running this command:
```yarn formatjs extract src/**/*.tsx --out-file lang/en.json --id-interpolation-pattern [sha512:contenthash:base64:6] --format formatter.js```

Throw errr:

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:377:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1076:11)
    at defaultResolve (node:internal/modules/esm/resolve:1156:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ESMLoader.import (node:internal/modules/esm/loader:404:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1043:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:435:21)
    at importModuleDynamically (node:vm:381:46)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
error Command failed with exit code 1.

## To Reproduce
Just put a formatter.js:
```
module.exports.format = function (msgs) {
  return Object.entries(msgs).reduce((acc, [id, msg]) => {
    return [
      ...acc,
      {
        term: id,
        definition: msg.defaultMessage,
        comment: msg.description,
      },
    ];
  });
};

module.exports.compile = function (msgs) {
  const results = {};

  for (const [id, msg] of Object.entries(msgs)) {
    results[id] = msg.definition;
  }

  return results;
};
```
Then run the extract command with custom formatter.

### Codesandbox URL

Please include a codesandbox URL if possible

### Reproducible Steps/Repo

1. Run the command
2. See error

## Expected behavior
The en.json file is well generated using the formatter.js format function.

## Screenshots

![image](https://user-images.githubusercontent.com/3867438/172058509-2ec20fed-1a3e-4f72-9260-953ffdabfd49.png)

## Desktop:

- OS: Windows 10
- Browser: NC
- Version: NC
- Node: 18.2.0
- @formatjs/cli: 5.0.1

**Comment by longlho** [comment]
You have to quote your path, different shells handle * differently

**Comment by marwen-cherif** [comment]
Hmm, 
I have tried using quotes, double quotes etc .., but i got the same each time,

![image](https://user-images.githubusercontent.com/3867438/172061020-3ff0fe51-04a1-42bd-a53c-6af89926af9d.png)

**Comment by longlho** [comment]
I mean quote the `"src/**/*.tsx"` part

**Comment by AndrewCraswell** [comment]
I'm encountering this too on Windows. I've also tried every kind of quotes and still throws the same error.

```
formatjs extract "src/**/*.{ts,tsx}" --ignore "src/**/*.{d,test}.{ts,tsx}" --out-file "src/__i18n__/strings.json" --id-interpolation-pattern [sha512:contenthash:base64:6] --format "../config/scripts/touchdownBuildFormatter.js"
```

Is it maybe related to how we're using relative pathing? I had to revert to our old version of `@formatjs/cli` which was `^3.0.1` which works properly.  I will try to see which version it breaks for me.

**Comment by AndrewCraswell** [comment]
It's working for me all the way up to version `4.8.4`. As soon as I bump to `5.0.0` it begins failing with the error.

**Comment by longlho** [comment]
do you have a codesandbox repro? I don't use Windows so not sure if this is a Windows issue

**Comment by smalljiaot** [comment]
I have the same issue with
```
 "formatjs extract \"apps/press-ui/src/**/*.ts*\" --ignore=\"apps/press-ui/src/**/*.d.ts\" --out-file \"apps/j.json\"  && formatjs compile \"apps/j.json\" --format \"./tools/scripts/DevTranslationFormatter.js\""
```

**Comment by longlho** [comment]
does anyone has a reproducible sample/codesandbox?

**Comment by Martin005** [comment]
@longlho This issue is happening only on Windows and the reason why it happens is described [in this Stack Overflow answer](https://stackoverflow.com/a/70057245).
The problem lies in [this import statement](https://github.com/formatjs/formatjs/blob/main/packages/cli-lib/src/formatters/index.ts#L40) – the `import()` function [only works with file:// and data:// URLs](https://nodejs.org/api/errors.html#err_unsupported_esm_url_scheme), but `path.resolve()` on Windows returns path which starts with the name of the local disk (e.g., `C:`).

One way around this issue is encapsulating the `resolve()` call in [`pathToFileURL` method from the url package](https://nodejs.org/api/url.html#urlpathtofileurlpath) method and importing the result of the outcome – **same way [Vue CLI did it](https://github.com/vuejs/vue-cli/blob/dev/packages/@vue/cli-service/lib/util/loadFileConfig.js#L28)**.

The `import` statement then takes the `href` property of the object (before and after):
![image](https://user-images.githubusercontent.com/10096404/182414448-465ac5c3-abbd-45fc-8c6b-2a2e5db84020.png)

**Comment by longlho** [comment]
Oh cool thanks for investigating. Wanna PR to fix real quick?

**Comment by Martin005** [comment]
@longlho PR is ready: #3741 :)
