### ISSUE TITLE
Lower or remove Node version requirement for @formatjs/cli-lib

### ISSUE THREAD

**Issue by lassegit** [formatjs/formatjs#3715]
## Which package?
`@formatjs/cli-lib` 

## Describe the bug
Since version 5 `@formatjs/cli` isn't dependent on Vue packages requiring a minimum Node version to work, thus rendering [formatjs/cli does not respect @vuejs/core's engines.node >= 16.5.0 requirement #3602](https://github.com/formatjs/formatjs/issues/3602) obsolete. Can we lower the Node engine required to say `14.x` or completely remove it? I reckon lot of projects are using lower version than `16.5` and then they can't benefit from the upgrade (which removed a lot of unneeded Vue dependencies).

`compiler-sfc` doesn't specify any particular Node version.  

Edit: Just updated this issue to be about `@formatjs/cli-lib` and not `@formatjs/cli`.

**Comment by lassegit** [comment]
@longlho What do you say? :)

**Comment by longlho** [comment]
technically we can lower it but we don't test against 14.x so there's no guarantee it actually works.

**Comment by lassegit** [comment]
In that case it makes sense, just unsure the percentage still using lower than version 16. But maybe not so many.

**Comment by abdel-ships-it** [comment]
@lassegit I think if this change is harmless, we should get rid of the `engine` requirement. I'm personally still on v14 due to certain constraints and cannot use this package because of that. 

Hearing `engine` requirement is there because of vue packages in the past, while being on react is somewhat frustrating. Having said that I would greatly appreciate it if you consider removing the `engine` requirement from the cli package. Thanks!
