### ISSUE TITLE
How does React-Intl recommend allowing users to select a different language?

### ISSUE THREAD

**Issue by alanhogan** [formatjs/formatjs#39]

**Comment by caridy** [comment]
ok ok, there is nothing (as far as I can tell) that will prevent you for doing all those things (even though we think those are crazy things jejejeje). The internal cache system used by react-intl will take in consideration the locales, and therefore if you change `locales`, `formats` and `messages` values, it will automatically create a new internal instance in cache when calling render().

As for the use of `context` under the hood to resolve locales, you can always avoid that by passing those props into every component in your application, that should do the trick since it will automatically resolve those values without trying to do so thru the context.

**Comment by sebastienbarre** [comment]
Thanks for all the pointers, guys. I have to admit I have a tough time making this work with Safari & webpack. If I use ```require.ensure``` to load ```intl``` from a separate chunk, it seems that it "finishes" loading it *after* the ```react-intl```'s mixins is evaluated from its own chunk, which results in an error because it is referencing ```intl``` already. I've described the problem in gpbl/react-locale-hot-switch#2.

**Comment by ericf** [comment]
@sebastienbarre not being able to use dependencies when a module is being executed seems like a problem with Webpack or how it's being configured. How are you conditionally loading other polyfills your app uses?

**Comment by sebastienbarre** [comment]
@ericf so far I had bit the bullet and included my polyfills in my vendor chunk, because they were pretty small. ```intl``` is... rather large. Using ```require('intl')``` brings a whopping 850+KB to the plate for some reasons (before minification), using ```require('intl/Intl')``` and just the en-US locale is about 150+KB, still pretty big, hence me trying to get by with ```require.ensure``` on that one...

**Comment by ericf** [comment]
The Intl polyfill + `en-US` is ~17kb gz IIRC. Hopefully we can land it in Polyfill.io which will make loading it and your other polyfills much simpler: https://github.com/Financial-Times/polyfill-service/issues/108

**Comment by sebastienbarre** [comment]
Yes, ultimately when UglifyJS has done its job and the server is gzipping, we are down to much smaller numbers. But I've to admit my surprise when I first tried ```require('intl')``` and saw my vendor chunk inflate so much. Looking forward what will happen with Polyfill.io. Thanks.

**Comment by gpbl** [comment]
@sebastienbarre my bad: the react-locale-hot-switch app wasn't using the react-intl@latest, which indeed requires `Intl` in the global scope. So you need to require `react-intl` in the webpack's `ensure` callback, hence *after* the polyfill has been loaded (see updated project).

**Comment by sebastienbarre** [comment]
@gpbl I see. Thanks a lot for the quick reply. It seems the change was made by @ericf  in e188cc1. 
```
exports["default"] = {
[...]
    getNumberFormat  : intl$format$cache$$["default"](Intl.NumberFormat),
    getDateTimeFormat: intl$format$cache$$["default"](Intl.DateTimeFormat),
    getMessageFormat : intl$format$cache$$["default"](intl$messageformat$$["default"]),
[...]
    _format: function (type, value, options, formatOptions) {
[...]
        switch(type) {
            case 'date':
            case 'time':
                return this.getDateTimeFormat(locales, options).format(value);
            case 'number':
                return this.getNumberFormat(locales, options).format(value);
            case 'relative':
                return this.getRelativeFormat(locales, options).format(value, formatOptions);
            default:
```
My gut feeling is that people will use the ```formatDate```, ```formatNumber```, etc. functions, not ```getNumberFormat```, etc. directly. Could they be initialized later? in ```_format``` maybe? Or simply turned into functions and a call to ```apply```?

It's not a huge issue, but the problem here is that it involves loading yet one more chunk, thus requiring yet another round-trip to the server. Performance-wise, you would want to avoid that.
For example:
```index.html```: load ```bootstrap.js``` using a ```<script>``` tag.
```bootstrap.js```: load ```Intl``` conditionally, using ```require.ensure```, which puts ```intl``` in its own chunk,
```bootstrap.js```: now that we have ```Intl``` (whether we had it already or not), load ```app.js``` using ```require```, which will ```require('react-intl')```, etc.
The consequence of this, is that webpack is going to create a separate chunk for ```bootstrap.js```, ```intl```, and ```app.js``` (since ```app.js``` is called in two different code paths). That's 3 round-trips. Previously we could get by with 2 round-trips. @ericf ? 

Again, thanks for the all the hard work.

**Comment by ericf** [comment]
> My gut feeling is that people will use the formatDate, formatNumber, etc. functions, not getNumberFormat, etc. directly. Could they be initialized later? in _format maybe? Or simply turned into functions and a call to apply?

This is like saying I can't access `Math` eagerly in my module and have to wait until a function is invoked before I can access it. The `Intl` APIs _must_ be available _before_ the code for React Intl is executed. This sounds like it will be a problem for you for any polyfill you conditionally load in your app. This is why the Polyfill.io solution is so attractive — you simple include a script to polyfill the runtime, then load your app code.

> The consequence of this, is that webpack is going to create a separate chunk for bootstrap.js, intl, and app.js (since app.js is called in two different code paths). That's 3 round-trips. Previously we could get by with 2 round-trips. @ericf ?

I would assume Webpack loads the `intl.js` and `app.js` chunks in parallel. This extra request for `intl.js` is only for browsers which don't have the `Intl` APIs built in. If your app only has three JavaScript HTTP requests you're doing really well!

**Comment by sebastienbarre** [comment]
Agreed, 3 separate requests wouldn't be too bad, I guess I was curious as to why I suddenly needed an extra one. I'm wholeheartedly with you on this one:
> The Intl APIs must be available before the code for React Intl is executed.

but I think that might be where the confusion is here, I'm not executing any React Intl code here, at all. I'm only loading my vendor bundle/chunk, where all the ```exports``` are. I noticed that issue in an app where only *one* page use i18n. The other pages do not. What I'm hinting at is that my user might never route to that i18n page, but the *whole* app fails to load now because my vendor chunk has 'react-intl', which makes this explicit reference to ```Intl```. I've to admit I've not have had that issue with other polyfills before, that's why I wold put them in my vendor chunk (small so far).

**Comment by henrylingumi** [comment]
Hi all, 

I came across this issue, and while it is old/closed I felt I might see if there's any new perspective from the React Intl team on how to allow users to select another language?

**Comment by Tomekmularczyk** [comment]
Hi guys, this is what I came up with with a new React Context API. Pure React solution, no redux required. Tell me what you think:


**IntlContext.jsx**
```javascript
import React from "react";
import Types from "prop-types";
import { IntlProvider, addLocaleData } from "react-intl";
import en from "react-intl/locale-data/en";
import de from "react-intl/locale-data/de";
import deTranslation from "../../lang/de";
import enTranslation from "../../lang/en";

addLocaleData([...en, ...de]);

const { Provider, Consumer } = React.createContext();

class IntlProviderWrapper extends React.Component {
  constructor(...args) {
    super(...args);

    this.switchToEnglish = () =>
      this.setState({ locale: "en", messages: enTranslation });

    this.switchToDeutsch = () =>
      this.setState({ locale: "de", messages: deTranslation });

    // pass everything in state to avoid creating object inside render method (like explained in the documentation)
    this.state = {
      locale: "en",
      messages: enTranslation,
      switchToEnglish: this.switchToEnglish, 
      switchToDeutsch: this.switchToDeutsch 
    };
  }

  render() {
    const { children } = this.props;
    const { locale, messages } = this.state;
    return (
      <Provider value={this.state}>
        <IntlProvider
          key={locale}
          locale={locale}
          messages={messages}
          defaultLocale="en"
        >
          {children}
        </IntlProvider>
      </Provider>
    );
  }
}

export { IntlProviderWrapper as IntlProvider, Consumer as IntlConsumer };
```

Main **App.jsx** component:
```javascript
import { Provider } from "react-redux";
import {  IntlProvider } from "./pages/common";

class App extends Component {
  render() {
    return (
      <Provider store={store}>
        <IntlProvider>
          ...
        </IntlProvider>
      </Provider>
    );
  }
}
```

**LanguageSwitch.jsx**
```javascript
import React from "react";
import { Text, Button } from "native-base";
import { IntlConsumer } from "../IntlContext";

const LanguageSwitch = () => (
  <IntlConsumer>
    {({ switchToEnglish, switchToDeutsch }) => (
      <React.Fragment>
        <Button onPress={switchToEnglish}>
          <Text>English</Text>
        </Button>
        <Button onPress={switchToDeutsch}>
          <Text>Deutsch</Text>
        </Button>
      </React.Fragment>
    )}
  </IntlConsumer>
);

export default LanguageSwitch;
```
