### ISSUE TITLE
Message extraction not working without default message

### ISSUE THREAD

**Issue by leonard-henriquez** [formatjs/formatjs#4001]
## Which package?

@formatjs/cli@6.0.3

## Describe the bug

In our team we are using `intl.formatMessage` with static id without default message (and we have a hard requirement to keep it this way).
Currently, the extract cli doesn't output keys.
How can we extract them ?

### Reproducible Steps/Repo

```js
intl.formatMessage({ id: 'static-id' });
```

```bash
# this command doesn't extract the key static-id to en.json
formatjs extract '**/*.{ts,tsx}' --format simple --out-file i18n/locales/en.json
```

## Expected behavior

We expect the formatjs extract command to add a new key `static-id` to the `en.json` file

**Comment by leonard-henriquez** [comment]
Is this library actively maintained ? 🥺

**Comment by longlho** [comment]
It is this request is just niche we haven't got time to look. PR is always welcome though

**Comment by ChiefORZ** [comment]
🤷‍♂️ thats not niche at all

**Comment by jonathan-chin** [comment]
just +1 here. our use case:

- separate development and content team
- content team is constantly tweaking copy text on app
- easier for development if we just have keys and descriptions
- ideal situation is if we can use `extract` to generate a json file with just keys and content team can compare with their old version of `en.json` (default language is English)
- content team hands us a new `en.json` and we use CI/CD to rebuild the app. that way, content team can work independently from development team and tweak verbiage to their heart's content

currently, our plan is to just have an empty string for all our `<FormattedMessage>` components for the defaultMessage prop. this seems to work. however, it is a not-insignificant amount of extra work since it poses maintainability concerns (what if a dev forgets to put an empty string? this error only comes when we run `extract`, which means we have to hunt down the file and line number to fix it).

a suggestion is to either make the default value for `defaultMessage` to be an empty string or add a CLI option to set default values for defaultMessage.

I'm happy to create a PR but definitely want to get feedback from the core team first.

**Comment by leonard-henriquez** [comment]
We needed that so we switched to https://lingui.dev/

**Comment by jonathan-chin** [comment]
> We needed that so we switched to https://lingui.dev/

it's going to very hard for us to pivot to a different solution since we have deadlines stacked up. I guess we could just use a different CLI; but we're also open to helping to improve FormatJS.

**Comment by longlho** [comment]
PR's always welcome. You can add additional flag to the CLI
