### ISSUE TITLE
`match` function from `intl-localematcher` matches wrong locale

### ISSUE THREAD

**Issue by borisghidaglia** [formatjs/formatjs#4272]
## Which package?

`@formatjs/intl-localematcher`

## Describe the bug

`match` function matches wrong locale

### Codesandbox URL

https://codesandbox.io/p/sandbox/happy-panini-tshqyf?file=%2Findex.js%3A1%2C1

### Reproducible Steps/Repo

Run the sandbox and check the log in the console.

## Expected behavior

Should match the "en" locale instead of the "fr" one.

## Desktop (please complete the following information):

Codesandbox environment

## Smartphone (please complete the following information):

Codesandbox environment

## Additional context

Hello 👋 
First of all thanks for your work on formatjs.
I had this issue in my code and noticed that [the second example on the doc](https://formatjs.io/docs/polyfills/intl-localematcher/) had the same. 

Example from the doc, works with `zh`:
```
match(['zh'], ['fr', 'en'], 'en') // 'en'
```

But doesn't work with `es`:
```
match(['es'], ['fr', 'en'], 'en') // 'fr'
```

Thanks for your help 🙏

**Comment by gabrielf** [comment]
Same here but with another example: `match(['es'], ['sv', 'en'], 'en') === 'sv'` (should be 'en')

**Comment by gabrielf** [comment]
Another interesting case: `match(['es-SV', 'en'], ['es', 'en'], 'en') === 'en'` (should it not be 'es' as 'es-SV' is Spanish in El Salvador?)

**Comment by gabrielf** [comment]
I've looked at the code trying to understand what's going on. The code is quite complex but it seems this behavior boils down to that the distance between `es` and `en` is longer/higher than between `fr` (or `sv`) and `en`. This is determined by the function  `findMatchingDistance`: https://github.com/formatjs/formatjs/blob/518d7cf35f0340b78cf6b899267018e98ff20ddb/packages/intl-localematcher/abstract/utils.ts#L148

Running just `findMatchingDistance` gives:

```ts
test('findMatchingDistance', () => {
  expect(findMatchingDistance('es', 'fr')).toBe(838)
  expect(findMatchingDistance('es', 'en')).toBe(840)
})
```

And the reason why `fr` is considered closer to `en` is because these lines: https://github.com/formatjs/formatjs/blob/518d7cf35f0340b78cf6b899267018e98ff20ddb/packages/intl-localematcher/abstract/utils.ts#L136-L141

Here the distance is decreased by 1 if one of the languages exists in `paradigmLocales` and one does not. Both `es` and `en` exists in `paradigmLocales`, so 1 is _not_ subtracted, but `fr` is not in `paradigmLocales` so 1 _is_ subtracted. The reason for the distance being 2 less for fr/es is that there are two subtractions being made, one when comparing just the languages and one when comparing the languages with their region in https://github.com/formatjs/formatjs/blob/518d7cf35f0340b78cf6b899267018e98ff20ddb/packages/intl-localematcher/abstract/utils.ts#L148

When using `match` the distance also depends on the order of supported locales as seen here: https://github.com/formatjs/formatjs/blob/518d7cf35f0340b78cf6b899267018e98ff20ddb/packages/intl-localematcher/abstract/utils.ts#L231

With this knowledge we can play around with the `supportedLocales` array:

```
// Note that the order of fr and en has been reversed
match(['es'], ['en', 'fr'], 'en') // still fr

// Here we insert greek between en and fr
match(['es'], ['en', 'gr', 'fr'], 'en') // en!

// We don't support greek so let's just insert duplicate en
match(['es'], ['en', 'en', 'fr'], 'en') // also en!
```

The first example is still `fr` because the difference in index between `en` and `fr` is smaller than the difference in distance between the languages and `es`.

I have no idea why the behavior is this way though… But I wouldn't be surprised if it is in accordance to some spec.

**Comment by borisghidaglia** [comment]
Thanks @gabrielf for your research and for the summary.
I hope this issue doesn't get closed 🙏

**Comment by longlho** [comment]
yeah the list of supported locales is a priority list which indicates your supported preference. Everytime we move down the list we add some penalty (arbitrarily `1` since spec doesn't dictate that). In this case, looks like we can apply `default` threshold before adding penalty to make sure the default locale is picked. Will take a look
