### ISSUE TITLE
[@formatjs/intl Error MISSING_DATA] should be a warning not an error

### ISSUE THREAD

**Issue by lfloyd117** [formatjs/formatjs#4352]
## Which package?

`@formatjs/intl` imported by `ember-intl`

## Describe the bug

At app boot we get the following logged as an error in Chromium based browsers, halting execution:
```
[@formatjs/intl Error MISSING_DATA] Missing locale data for locale: "eu-es" in Intl.NumberFormat. Using default locale: "eu-es" as fallback. See https://formatjs.io/docs/react-intl#runtime-requirements for more details
```
Chromium stopped supporting eu-es and is-is locales, which we localize for. This has been the case for a long time and yet our localization has still worked in those locales.
When we upgraded from `ember-intl` v5.7 to v6.4, it added `@formatjs/intl@2.9.9` and we now get this error from formatjs. 

This is an app breaking error when something like this should be a warning or at very least configurable. 

We can get around the error somewhat using the `@formatjs/intl` polyfills, but despite lazily loading our translations depending only on what one we are using, we get errors unless we add polyfill locale-data for EVERY SINGLE locale we support, which adds 3MB to our bundle size. 
If we just lazy load the polyfills with the locales that need them, we still get errors. 

If there is a better way to handle this I am all ears, but it seems being able to log this as a warning would be ideal. 

## To Reproduce

1. Use "eu-es" or "is-is" locale on a Chromium based browser
2. Observe

## Expected behavior

No error, a warning at most

## Screenshots
![image](https://github.com/formatjs/formatjs/assets/127987457/39c29067-6326-4e2e-836c-7dc4f12f7437)

**Comment by ijlee2** [comment]
Hello, to the maintainers of `@formatjs`, I'm the current maintainer of [`ember-intl`](https://github.com/ember-intl/ember-intl).

I reproduced the error message described above, using `ember-intl`'s documentation app. I learned that, [by default, `ember-intl` re-throws errors from `@formatjs/intl`](https://github.com/ember-intl/ember-intl/blob/v6.4.0/ember-intl/addon/services/intl.js#L132-L136).

So I reached out to @lfloyd117 on [Ember Discord](https://discord.com/channels/480462759797063690/483601670685720591/1205800887302234184) and recommended that they patch the file `addon/services/intl.js` (e.g. using `patch-package` or `pnpm patch`), partly because the current implementation of `onIntlError()` hasn't affected many other users of `ember-intl`:

```js
onIntlError(error) {
  switch (error.code) {
    case IntlErrorCode.MISSING_DATA: {
      // Temporarily ignore errors caused by Chromium for `eu-es`
      console.warn(error.message);

      break;
    }

    case IntlErrorCode.MISSING_TRANSLATION: {
      // Do nothing
      break;
    }

    default: {
      throw error;
    }
  }
}
```

I think this minimal change is the best, temporary solution to help them update `ember-intl` to `6.4.0`. We may be able to close this issue as a result. (Still, it'd be good if there's a way to fix errors caused by Chromium for `eu-es`.)

Best,

**Comment by lfloyd117** [comment]
Thank you so much, @ijlee2 , that worked for us silencing these errors. 
I will let the maintainer decide if the issue should be closed or not for if this is a more widespread issue for other developers supporting languages that Google doesn't.

**Comment by longlho** [comment]
This is already a non-breaking error as it falls back to the default locale.
