### ISSUE TITLE
Polyfill.io has been sold to a weird Chinese company and should no longer be recommended

### ISSUE THREAD

**Issue by renchap** [formatjs/formatjs#4363]
## Which package?

Documentation

## Describe the bug

Polyfill.io was owned by the Financial Times web team, then moved under community management, and the last maintainer sold the project to a weird Chinese CDN company, and they moved it away from Fastly (the CDN / Edge compute platform running the OSS code for the service) and started to mess with the returned files.

From polyfill.io original creator: https://twitter.com/triblondon/status/1761852117579427975

Issue on their repo: https://github.com/polyfillpolyfill/polyfill-service/issues/2834

The domain polyfill.io is now a CNAME to polyfill.io.bsclink.cn, there has been no communication about this, or how the service is now ran (it previously depended on Fastly's edge compute platform, which is not available on this chinese cloud).

Fastly, who were not involved in this, but provided the service for free as part of their [Fast Forward program](https://www.fastly.com/fast-forward), informed us that https://polyfill-fastly.io/ is an alternative domain they setup to help people move away from Polyfill.io, but this is probably not a long-term solution.

### Codesandbox URL

https://formatjs.io/docs/polyfills/intl-locale/

### Reproducible Steps/Repo

1. See that polyfill.io is a recommended way to install the Polyfill

## Expected behavior

The docs do not recommend loading polyfills from a no-longer trusted and transparent source

**Comment by SukkaW** [comment]
`polyfill.io` was acquired by **a China-based CDN company** "Funnull", see [the announcement from the `polyfill.io` domain owner's Twitter](https://x.com/JakeDChampion/status/1761315227008643367) and https://github.com/polyfillpolyfill/polyfill-service/issues/2834. Despite Funnull's claims of operating in the United States, the predominance of Simplified Chinese on its website suggests otherwise, and it turns out that **"Funnull" is notorious for providing service for the betting and pornography industries**.

[The original creator of the `polyfill.io` has voiced his concern on Twitter](https://twitter.com/triblondon/status/1761852117579427975). And since the acquisition, numerous issues have emerged (https://github.com/polyfillpolyfill/polyfill-service/issues/2835, https://github.com/polyfillpolyfill/polyfill-service/issues/2838, https://github.com/alist-org/alist/issues/6100), rendering the `polyfill.io` service **extremely unstable**. Since then, Fastly ([Announcement](https://community.fastly.com/t/new-options-for-polyfill-io-users/2540)) and Cloudflare ([Announcement](https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk)) has hosted their own instances of `polyfill.io` service.

**Comment by dir** [comment]
https://www.bleepingcomputer.com/news/security/polyfillio-javascript-supply-chain-attack-impacts-over-100k-sites/

This issue was ahead of it's time. Good call out.

**Comment by fproulx-boostsecurity** [comment]
Damn, indeed you had the eyes on the ball, long ago
