### ISSUE TITLE
Thousands separator does not work well in Spanish

### ISSUE THREAD

**Issue by Borjaapi** [formatjs/formatjs#4486]
Which package?
intl

Describe the bug
the thousands separator works only when the number has at least four digits

To Reproduce
Codesandbox URL
https://codesandbox.io/p/sandbox/quirky-tristan-5r8fjx

Reproducible Steps/Repo
if you click on the “EN” button you can see the English thousands separator.
if you click on the “ES” button you can no longer see the thousands separator for Spanish.

Expected behavior
It should be possible to read "3.566 números"

Screenshots
![image](https://github.com/user-attachments/assets/0d374e51-16d5-44bc-a8bd-25d76f27dafb)
![image](https://github.com/user-attachments/assets/0d1586ef-7f94-4efb-8b6d-e89b60008bb0)

Desktop (please complete the following information):
OS: Windows 10
Browser Edge
Version 126.0.2592.102 (Official build) (64-bit)

**Comment by harrymaynard** [comment]
From the documentation:

> Values can also be formatted based on their type. You use a {key, type, format} argument to do that.
> Internally it uses the Intl.NumberFormat API. You can define custom values for the format element, which are passed to the Intl.NumberFormat constructor.

I've tried the JS native helper `Intl.NumberFormat` and ran `new Intl.NumberFormat("es").format(1234)`, and it returns `"1234"`, however if you add another digit `new Intl.NumberFormat("es").format(12345)`, it returns `"12.345"` as expected. I think this issue comes down to the native JS standard for `Intl.NumberFormat` under `es` locales. If you wish to deviate from the standard, then unfortunately it looks like you need to write it yourself. So something like the following:
```js
function formatNumberToEsLocale(number) {
  return number.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
}
```

If you're stuck with formatjs, then here's some links the documentation:
https://formatjs.io/docs/core-concepts/icu-syntax#number-type

https://unicode-org.github.io/icu/userguide/format_parse/numbers/skeletons.html#examples

Hope that helps!
