### ISSUE TITLE
FormattedMessage return types incompatible with React 17

### ISSUE THREAD

**Issue by weedgrease** [formatjs/formatjs#4572]
## Which package?
`react-intl@^6.8.0`

Since this is a monorepo. Please specify which package this bug report is for.

## Describe the bug

`FormattedMessage` return type is now incompatible with React 17. I would consider this a bug unless `react-intl` is dropping support of React 17 in favor of 18 and soon 19.

```
'FormattedMessage' cannot be used as a JSX component.
  Its element type 'string | number | boolean | ReactElement<any, string | JSXElementConstructor<any>> | Iterable<ReactNode> | Component<...> | null | undefined' is not a valid JSX element.
    Type 'undefined' is not assignable to type 'Element | ElementClass | null'.
```

### Codesandbox URL

[Codesandbox VM](https://codesandbox.io/p/github/weedgrease/react-intl-react-17/master)

### Reproducible Steps/Repo

1. Upgrade `react-intl` to its latest version (6.8.0) in a React 17 app
2. Render a `<FormattedMessage />` inside of any component
3. See type error conflicting with React types that `FormattedMessage` cannot be used as a JSX component

## Expected behavior

I would expect `react-intl` to continue to not throw type errors with earlier versions of React since no peer dependency is mentioned about a specific React version.

## Desktop (please complete the following information):

- OS: Windows
- Browser: Chrome

## Additional context

There are two potential commits that I saw that introduced this behavior change:
https://github.com/formatjs/formatjs/commit/a43c8ab54ab9d74e712bd4dfe68bb879ec369b3b
https://github.com/formatjs/formatjs/commit/96725cb37e4a7d4749d9399c2d9b69862dcd2b4b

Is React 17 support being dropped?

**Comment by renestalder** [comment]
Currently, blocks any updates. It would be nice to know whether this is the wanted behaviour going forward or not.

**Comment by longlho** [comment]
thanks for reporting. We'll take a look soon.

**Comment by rodoabad** [comment]
I don't mind this update if the `react-intl` team is now looking to support React 18+. From a TS-based project, this should be a breaking change release.

**Comment by kcchoate** [comment]
I've run into this issue as well. From my cursory glancing, the incompatibility looks to be coming from [this change](https://github.com/formatjs/formatjs/commit/21b2e7130585f42aeafadbaf9f332d7be3c213ee#diff-8e80bc6a06aa544f9d29846294c3eee9ffe0ff5bbdf612ee602897ddffa786e3L137) (GH's new commit UI is failing to take me straight to the line in question when I click that link, it is `packages/react-intl/package.json:L137`). That change is now causing the React 18 typings to be downloaded if they weren't already, which in turn causes Typescript to pick them up and throw errors if you aren't already on a similar version.

This issue is preventing me from upgrading past `6.6.8` which is the last version without this change in dependency versioning. It would be great to know if this is an intentional change (in which case `react-intl`'s peerDependencies should be updated), or an unintentional change which will be reverted. Thanks!

**Comment by longlho** [comment]
@weedgrease I can't even `npm install` in the codesandbox example :-/ seems like `react-scripts` doesn't support TS5

**Comment by longlho** [comment]
https://codesandbox.io/p/sandbox/f9r9p5?file=/src/App.tsx:13,1 I can't see any issue in this codesandbox

**Comment by kcchoate** [comment]
Hi @longlho. I've confirmed that [this commit](https://github.com/formatjs/formatjs/commit/d8f6047c291a545eb8690290f7bc7761838e5c86) in `6.8.6` has fixed my issue. Thank you!
